config-version: 2
name: 'quickbooks'

version: '0.17.1'

require-dbt-version: [">=1.3.0", "<2.0.0"]

profile: quickbooks

models:
  quickbooks:
    +materialized: table
    +schema: quickbooks
    double_entry_transactions:
      +schema: quickbooks_intermediate
      +materialized: table
    transaction_lines:
      +materialized: ephemeral
    intermediate:
      +materialized: ephemeral
vars:
  quickbooks:
    account: "{{ ref('stg_quickbooks__account') }}"
    address: "{{ ref('stg_quickbooks__address') }}"
    bill_line: "{{ ref('stg_quickbooks__bill_line') }}"
    bill_linked_txn: "{{ ref('stg_quickbooks__bill_linked_txn') }}"
    bill_payment_line: "{{ ref('stg_quickbooks__bill_payment_line') }}"
    bill_payment: "{{ ref('stg_quickbooks__bill_payment') }}"
    bill: "{{ ref('stg_quickbooks__bill') }}"
    bundle_item: "{{ ref('stg_quickbooks__bundle_item') }}"
    bundle: "{{ ref('stg_quickbooks__bundle') }}"
    credit_memo_line: "{{ ref('stg_quickbooks__credit_memo_line') }}"
    credit_memo: "{{ ref('stg_quickbooks__credit_memo') }}"
    credit_card_payment_txn: "{{ ref('stg_quickbooks__credit_card_payment_txn') }}"
    customer: "{{ ref('stg_quickbooks__customer') }}"
    department: "{{ ref('stg_quickbooks__department') }}"
    deposit_line: "{{ ref('stg_quickbooks__deposit_line') }}"
    deposit: "{{ ref('stg_quickbooks__deposit') }}"
    estimate: "{{ ref('stg_quickbooks__estimate') }}"
    estimate_line: "{{ ref('stg_quickbooks__estimate_line') }}"
    invoice_line: "{{ ref('stg_quickbooks__invoice_line') }}"
    invoice_line_bundle: "{{ ref('stg_quickbooks__invoice_line_bundle') }}"
    invoice_linked_txn: "{{ ref('stg_quickbooks__invoice_linked_txn') }}"
    invoice: "{{ ref('stg_quickbooks__invoice') }}"
    item: "{{ ref('stg_quickbooks__item') }}"
    journal_entry_line: "{{ ref('stg_quickbooks__journal_entry_line') }}"
    journal_entry: "{{ ref('stg_quickbooks__journal_entry') }}"
    payment_line: "{{ ref('stg_quickbooks__payment_line') }}"
    payment: "{{ ref('stg_quickbooks__payment') }}"
    purchase_line: "{{ ref('stg_quickbooks__purchase_line') }}"
    purchase: "{{ ref('stg_quickbooks__purchase') }}"
    refund_receipt_line: "{{ ref('stg_quickbooks__refund_receipt_line') }}"
    refund_receipt: "{{ ref('stg_quickbooks__refund_receipt') }}"
    sales_receipt_line: "{{ ref('stg_quickbooks__sales_receipt_line') }}"
    sales_receipt: "{{ ref('stg_quickbooks__sales_receipt') }}"
    transfer: "{{ ref('stg_quickbooks__transfer') }}"
    vendor_credit_line: "{{ ref('stg_quickbooks__vendor_credit_line') }}"
    vendor_credit: "{{ ref('stg_quickbooks__vendor_credit') }}"
    vendor: "{{ ref('stg_quickbooks__vendor') }}"

    financial_statement_ordinal: []
    cash_flow_statement_type_ordinal: []

    using_address: false
    using_bill: true
    using_credit_memo: false
    using_department: false
    using_deposit: false
    using_estimate: false
    using_invoice: false
    using_invoice_bundle: false
    using_journal_entry: false
    using_payment: false
    using_refund_receipt: false
    using_transfer: false
    using_vendor_credit: false
    using_sales_receipt: false
    using_credit_card_payment_txn: false

analysis-paths: ["analysis"]
clean-targets:
- target
- dbt_modules
- dbt_packages
